### ISSUE TITLE
Instructional videos

### ISSUE THREAD

**Issue by mayacakmak** [mayacakmak/se2#11]
Here is the completed video for one of the interfaces:
https://youtu.be/-bwEiM_2Ur8

Any feedback/sticking point/missing things before I move onto making the other 7 videos? @KaviMD 

Once videos are finalized we need to update instructions.html to (1) get which interface the participant is using from the URL, (2) display the correct video for each interface, and (3) figure out the pipeline from MTurk to the full set of interfaces (probably different HITs for each interface, then each HIT has a different link with the URL parameters).

**Comment by kavidey** [comment]
The only thing that I can think of to add might be that after the questionnaire, users will receive a completion code to enter into MTurk. That might be unnecessary for people who are very familiar with MTurk though. Other than that, I think the video looks good

**Comment by mayacakmak** [comment]
Five videos done.. four more to go (I realized a click based interface is also possible for the panel control and might be a good alternative)

Drag: https://youtu.be/A-mzWlPjxDU
Arrows: https://youtu.be/8jFbHrpaptU
Target: https://youtu.be/YEVwIV0PPDE
Panel: https://youtu.be/B8QkeA3O_RY
Ring-click: https://youtu.be/-qUV753YINg

**Comment by csemecu** [comment]
The videos look great! I think it is very clear the steps they need to take. One thing that I didn't know and realized with the videos is that the "I'm ready" sign is actually a button and that's how you start the next one with the countdown. So actually the "next" button is only to go to the questionnaire section after they are done

**Comment by kavidey** [comment]
I'm working on adding the videos to the instructions.html page, right now it seems like the Ring-click video is set to private, I'm not sure if that's just a bad link or something.

**Comment by mayacakmak** [comment]
Ah yes, that video's settings were not saved yet, should work now. I'll finish the other videos today, maybe we can launch during our meeting ;)

**Comment by kavidey** [comment]
I added a counter and interface selection system to the database and updated instructions.html, enabled logging, and cleared all the data from firebase.

Aside from finalizing the questionnaire, I think that all we need to do is update [this file](https://github.com/mayacakmak/se2/blob/master/scripts/instructions.js#L6) with the final set videos!

**Comment by mayacakmak** [comment]
Final list of videos, also added them into instructions.js

Drag: https://youtu.be/A-mzWlPjxDU
Arrows: https://youtu.be/8jFbHrpaptU
Target: https://youtu.be/YEVwIV0PPDE
Panel: https://youtu.be/B8QkeA3O_RY

Arrows-click: https://youtu.be/ADlGCOGRjxc
Drag-click: https://youtu.be/W2uMjeDp4LI
Target-click: https://youtu.be/VpbocBmKBLk
Panel-click: https://youtu.be/Y_t3GDRDD_s
Ring-click: https://youtu.be/-qUV753YINg
