### ISSUE TITLE
Browser/system check

### ISSUE THREAD

**Issue by mayacakmak** [mayacakmak/se2#14]
We probably need to tell people to use Chrome on a desktop. Could we automatically detect if people are on a mobile device and not let them participate? @KaviMD

**Comment by kavidey** [comment]
Yes, I can add a check to instructions.html. If they are on a mobile device should we just redirect them to a page that asks them to load the page on a desktop?

**Comment by kavidey** [comment]
I just added code to [instructions.html](https://github.com/mayacakmak/se2/blob/master/instructions.html#L45) that redirects any mobile users to [mobile.html](https://mayacakmak.github.io/se2/mobile) (`mobile.html` instructs the user to load https://mayacakmak.github.io/se2/instructions.html on a desktop or laptop computer)

**Comment by mayacakmak** [comment]
Yes! Either redirect or change the content of instructions.html to say something like "Sorry, this study is not available on a mobile device. Please use a Chrome bowser on a personal computer (laptop or desktop)." and for the browser error "Sorry this study requires a Chrome browser" (maybe it works fine on other browsers, but might not be worth the time testing).

**Comment by kavidey** [comment]
I added a separate clearer error for [mobile](https://mayacakmak.github.io/se2/errors/mobile_error.html) vs [chrome](https://mayacakmak.github.io/se2/errors/chrome_error.html) like you suggested (I tested the mobile device detection against several androids an iPhones, and the browser detection against Safari, Firefox, and Microsoft Edge)

**Comment by mayacakmak** [comment]
Awesome!
